# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparse_matrix', '0002_auto_20160324_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparse',
            name='length',
            field=models.IntegerField(unique=True),
        ),
    ]
