# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fibonacci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fibonacci_no', models.IntegerField()),
                ('recursive_time', models.FloatField()),
                ('iterative_time', models.FloatField()),
                ('cpu_time', models.FloatField()),
            ],
        ),
    ]
