# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonacci',
            name='cpu_time',
            field=models.FloatField(default=0),
        ),
    ]
